[package]
name = "everybody-codes"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = { version = "0.6", default-features = false }

# https://github.com/eyre-rs/eyre/tree/master/color-eyre#improving-perf-on-debug-builds
[profile.dev.package.backtrace]
opt-level = 3
